### ISSUE TITLE
Property editors: base font size and font-weight

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#1025]
### Description

It appears that the current font size and font weight that is used for displaying values in property editors as selection criteria on Entity Centres do not allow for immediate distinction between property titles and values. This makes it difficult to easily see which selection criteria have values and which do not.

A screen capture below demonstrates highlighting of selection criteria with applied mnemonics as well as larger and bolder selection criteria values.

![image](https://user-images.githubusercontent.com/5511940/42008158-62db7fac-7ac7-11e8-8622-5bb0020d60ff.png)

Increasing property values to `16px` and using `font-weight` with value `500` should provide the desired effect to ease the visibility of values vs. titles.

This problem is also related to iPhone devices whereby editor focusing causes zoom-in effect. This is complemented with soft keyboard appearance and the editor cursor appearance. Once the editor looses its focus and the keyboard disappears, the zoom-in factor remains remains the same. This also causes inconsistent layouting of the autocompleter overlays (more details are available [here](https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone)).

It is proposed that the new styling of property values is applied consistently to both selection criteria on Entity Centres and property editors on Entity Masters.

### Expected outcome
Improved visibility of property values on Entity Centres (selection criteria) and Entity Masters as well as the resolution of the undesired auto zoom-in behaviour for iOS devices.

**Comment by 01es** [comment]
The screenshots below illustrate how selection criteria and master look after the applied changes. Selection criteria and property values are now a lot easier to distinguish from titles.

![image](https://user-images.githubusercontent.com/5511940/42979753-3d256924-8c17-11e8-8dae-4662ef1d772f.png)

![image](https://user-images.githubusercontent.com/5511940/42979761-4325eaec-8c17-11e8-9694-f9d8af961fd6.png)

**Comment by McDonalP** [comment]
Its certainly a lot better, however wondering if the enlarged text has gone a notch too far (can it be a little smaller?). Making them bold is very good.
