### ISSUE TITLE
Auto-resize simple master if window size is too small

### ISSUE THREAD

**Issue by elvin-fms** [fieldenms/tg#1085]
### Description
Compound masters already automatically reduce their height if the height of the browser window is not sufficient for the default height. 
Need to enhance the behaviour of simple masters in the similar way.

### Expected outcome
Buttons Save and Cancel are visible upon opening of simple masters, which are too tall to fit into the browser window.

**Comment by 01es** [comment]
Changes in this issue improve the fit-to-window behaviour for both Simple and Compound Masters.
