### ISSUE TITLE
Chrome 74 (beta): changes to Flex Layout break the default appearance of insertion points

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#1311]
### Description
Chrome 74 (beta), which is to be release at the end of April, 2019, changes the behaviour of Flex Layout yet again. Previous changes to Flex Layout in version 72 broke scrolling (#1242). This time, changes affect the default size of insertion points, which now appear "collapsed". 

Insertion points are used to representing "additional" information on Entity Centres, such as charts. Although, collapsed insertion points can be expended to a "full screen" view, many are intended to be used together with the main EGI or other insertion points in their default position and size. Therefore, this most recent anomaly needs to be addressed as a matter of hight priority.

### Expected outcome
Properly sized insertion points.

### Actual outcome 
Collapsed insertion points.

### Steps to reproduce
Open any Entity Centre with one or more insertion point to see them "collapsed".

#### Browsers
- Chrome 74 (beta)

**Comment by TYearsley** [comment]
Thanks Oles
We'll manage this internally until the next release.
