### ISSUE TITLE
Master's height increased problem.

### ISSUE THREAD

**Issue by oleh-maikovych** [fieldenms/tg#1345]
### Description

Some masters which had specified dimension now look even more tall which causes shadow to appear. Please make sure that all paddings and editor dimensions are the same as in Polymer 1 version.
![image12](https://user-images.githubusercontent.com/5980808/59672929-15b2bc80-91c9-11e9-8ae8-1fe759b6c92b.png)

**Comment by 01es** [comment]
This change has some performance implications. Also, it impedes visibility of underlines even at 75% zoom. Prefer to leave the default style and to adjust the relevant Entity Masters to accomodate the new default height of property editors.
