### ISSUE TITLE
Further performance improvements for masters and selection criteria with lots of editors

### ISSUE THREAD

**Issue by jhou-pro** [fieldenms/tg#1387]
### Description
As part of Web Components / Polymer upgrade initiative we have optimised editors and supporting infrastracture to achieve acceptable performance under Web Components spec1 / Polymer 3. However the performance is still needed to be improved, especially under iPad devices.

### Expected outcome
Better performance for loading of masters and selection criteria with lots of editors.

**Comment by 01es** [comment]
This issue was used for preliminary investigation of Polymer 3 performance problems, and is no longer relevant.
