### ISSUE TITLE
Represent the title of a module menu item in the browser tab

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#1388]
### Description
At the moment the document title for TG applications is static and reflects the application name and version.

Based on the user feedback, there is a need to update the document title dynamically based on a module menu item loaded. This is especially convenient in cases where multiple browser tabs or windows are used.

In most cases module menu items represent Entity Centres, which may have a custom configuration loaded. The document title should have the same value as the one for the centre. Moving away from a module menu item to the main menu should restore the document title to its static value (i.e. application name and version).

![image](https://user-images.githubusercontent.com/5511940/62501909-2af2b180-b830-11e9-9bb6-6898d128ef95.png)

#### Implementation remark
Document title can be changed by assigning `document.title = ...`.

### Expected outcome
Improved usability in the multi-tab and multi-window configuration.

**Comment by mouatt** [comment]
The solution looks good. I have approached the TC's (The original requester of this improvement) for their feedback and they are happy as well.
