### ISSUE TITLE
Autocompleter: making the web component leaner

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#1391]
### Description

Recognising the fact that performance is a feature and in a continuous strive for excellency, the implementation of property editor `tg-entity-editor` (aka autocompleter) should be optimised for performance by replacing declarative use of its subcomponent `tg-entity-editor-result` in favour of an imperative, but more performance way. More specifically, instances of `tg-entity-editor-result` should be created ad-hoc at the time when it is needed by using the well established `dom-bind`/`innerHtml` approach.

Our analysis suggests that in some cases (i.e. masters and centres with multiple entity editors) this optimisation should result in over 30% performance improvements.

### Expected outcome
Improved time for instantiation of views with multiple entity editors.

**Comment by oleh-maikovych** [comment]
Single selection autocompleter doesn't work. It always select first item when tapping on any item.
