### ISSUE TITLE
Entity masters: cancelling changes to existing entities closes the master

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#1421]
### Description

It has been identified that the behaviour of CANCEL on Entity Masters has a regression where cancelling changes to existing entities closes the master.

This regression needs to be rectified in accordance with the original specification in issue #916.

_Remark: when testing Web UI as part of migration to Web Components v1, this functionality had been tested -- the test plan includes an item for "closing" of Entity Masters and retesting previous application releases proves it was working as expected; Most likely this regression was introduced recently as part of issue #1416._

### Expected outcome
The intended behaviour as per issue #916.

**Comment by mouatt** [comment]
Could this issue be done as a hot fix please.
