### ISSUE TITLE
Entity Centre: scrolling configuration API violates the previous contract for fixed columns

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#1422]
### Description

The call to 
```Java
ScrollConfig.configScroll().withFixedCheckboxesPrimaryActionsAndFirstProps(firstPropsToFix)
```
was suppose to make the primary action column and the first `firstPropsToFix` property columns "fixed".

Since the migration to Web Components v1, this contract became violated, and instead `firstPropsToFix` is treated as the number of columns to be "fixed", including the primary action column.

For example, calling `.withFixedCheckboxesPrimaryActionsAndFirstProps(1)` would only fix the primary action column, not the primary action column and the first property column.

This regression needs to be addressed.

### Expected outcome
Valid correspondence between the API and actual behaviour. Argument `firstPropsToFix` should mean the number of **property columns** to be fixed.

**Comment by oleh-maikovych** [comment]
This is not regression of the EGI and how it treats `withFixedCheckboxesPrimaryActionsAndFirstProps` invocation. The reason of such effect might be the presence of invisible columns which are in the beginning of the column list.
