### ISSUE TITLE
Entity usage: open reference hierarchy

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#1426]
### Description

As developers we enjoy powerful tools that modern IDEs provide. One of such tools is "Open Call Hierarchy" that gives us the ability see where in the code a function is called. This information facilitates our analysis of the code base -- what depends on that function, what impact its refactoring may have, etc.

Similarly, end users of our solutions would greatly benefit from having the ability to find what entities in their system reference an entity of interest. For example, user may need to know what work orders and assets reference a specific document. By representing such information hierarchically, users will be empowered to drill down to see where those entities are referenced in turn.

Having a domain model underpinning TG applications, naturally provides a capability to generate relevant queries from the model and build a hierarchy of references. And having support for representing hierarchical structures as part of Web UI, we can put the two together to create a very powerful tool for our users.

### Expected outcome
The ability by users to find entity usage as a hierarchy of references.

**Comment by mouatt** [comment]
Would you be able to provide a rough time-frame for when this enhancement may be worked on?

**Comment by 01es** [comment]
@mouatt We were just discussing this issue yesterday with @elvin-fms! This issue was thought of more as a nice-to-have. There are more pressing issues at the moment such as generic auditing (#538) and notification centre (#1072).

However, if the functionality defined in this issue is of interest, it can certainly be prioritised.

**Comment by mouatt** [comment]
The other two issues will provide some good support tools and functionality. The auditing issue looks like it may take a while to create but will be great for auditing and analysis.
This issue is one that will allow our users to find information quicker/easier and in some cases find records that are linked to each other where it currently isn't possible through the GUI - something I would currently have to do via an SQL query so it's a bit more than a nice-to-have.
I will leave it up to you to prioritise the platform issues but just thought I would ask about this enhancement due to having a few teams that would greatly benefit from this functionality being available.

**Comment by 01es** [comment]
Here is a sketch of the reference hierarchy tree. 

![image](https://user-images.githubusercontent.com/5511940/78525945-e6cf0b00-781b-11ea-9e68-1d46702317c7.png)

The root node of the tree is not displayed, but is assumed and represents an entity instance that is being analysed. Let's refer to a corresponding entity instance as `ref` instance. As the tree is being expanded, nodes representing entity instances on every odd level (2, 4, ...) become `ref` instances for their reference hierarchy sub-tree. 

Structurally, the tree is a repetition of 2 distinct kinds of nodes `Types -> Instances -> Types -> Instances ->...`. We can think of that as 2 alternating levels of nodes `Types` and `Instances`:

- `Types` form the first kind of nodes (let's call them Level 1), these nodes represent entity types that have instances referencing the `ref` instance.

- `Instances` form the second kind of nodes (lest call them Level 2), these nodes represent instances of a type that reference the `ref` instance.

The structural diagram below illustrates a tree fragment, outlining the data needed to produce EQL models to retrieve the data for different tree levels.

Nodes at the level of `Types` (Level 1) require `refId` and `refType` that represent the `ref` instance. This is required to build a query for retrieving the actual instances that reference `ref` instance. As the result, each such node also carries `type` representing entities referencing the `ref` instance, and the total number of references of this type to the `ref` instance as `count`.

Nodes at the level of `Instances` (Level 2) do not really require `refId` and `refType` (indicated with the orange rectangles) as they are **not** used for anything, and may be omitted. Nodes at this level assume the role of the `ref` instance themselves when one tries to expand them. Attribute `id` and `type` is then used in the same capacity as for the very initial `ref` instance -- to build a query to retrieve the data necessary for the next Level 1 of `Types`, but this time referencing a completely different entity instance.

![image](https://user-images.githubusercontent.com/5511940/78529414-e5561080-7824-11ea-850b-b56617fa43d1.png)

**Comment by 01es** [comment]
Based on the additional information received from customers and after more in-depth usage testing, it became apparent that "References" information is required in addition to the originally required "Referenced By" information.

"References" should consist of non-empty entity-typed properties that "this" entity instances references. It is proposed to introduce two grouping nodes "References" and "Referenced By" at the level of instance nodes (starting with the root entity) in order to separate references into two specific groups.

The sketch below illustrates changes suggested. Please note that each reference-node (either the one referenced, i.e. property, or the one referencing) should now have action "Open Reference Hierarch" in addition to "Open Master". This will provide users with the ability to "jump" between reference hierarchies of different entity instances.

![image](https://user-images.githubusercontent.com/5511940/80336782-93d8f880-889b-11ea-9e0d-c3b684b6d266.png)

**Comment by 01es** [comment]
Minor improvement was made recently https://github.com/fieldenms/tg/pull/2148/commits/2f1731853bf98bd025ceb3f4a1b91e685d5d95d2
