### ISSUE TITLE
Entity Master: open master action from entity-typed property editors, existing values

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#1521]
### Description

Entity editors on Entity Masters should be equipped with the "open master" action by default, enabling user to navigate conveniently between Entity Masters.

Property editor already support property-specific actions and this "slot" should not be taken by the default "open master" action. We also do not want to "pollute" the UI with additional elements. This is why it is proposed to use the property editor title to associate the generic action for opening Entity Masters.

![image](https://user-images.githubusercontent.com/5511940/80456079-5003f300-8970-11ea-9b53-491a32fabbfa.png)

The look and feel of the title should change only when the mouse cursor is hovering over it, in order to indicated that it can be clicked. A small "arrow" icon could become visible at the end of the title and a helpful tooltip could advise of the possible action.

#### Remark

The default "open master" action should only be applicable if a corresponding entity type has a master, and only if the entity editor is bound to the currently displayed entity value.

### Expected outcome
Further improvements to UI/UX of TG-based solutions by means of making navigation between Entity Masters as easy and convenient as possible.

**Comment by 01es** [comment]
@oleh-maikovych additional usability testing suggests that displaying a visual cue for a property editor is required not only when its title is hovered over with a mouse cursor, but also when:

- [ ] Hovering over an editor (i.e. the input field).
- [ ] When an editor is in focus – this is especially needed for mobile representation where is no mouse cursor.

**Comment by jhou-pro** [comment]
Tooltip for entity editor without edit action has `false` in the end. This happened due to changes in the tooltip generation logic provided by this issue. This should be fixed.
