### ISSUE TITLE
Security Matrix performance issue on Chrome 84 beta

### ISSUE THREAD

**Issue by oleh-maikovych** [fieldenms/tg#1545]
### Description

Chrome 84 beta becomes unresponsive while opening security matrix master. 

### Expected outcome

Investigate the reason why security matrix causes Chrome to hang.

#### Browsers
- Chrome 84 beta

**Comment by 01es** [comment]
This turned out to be a defect in Chrome 84 beta. The released Chrome 84 has this defect resolved.
