### ISSUE TITLE
EGI editing enhancement.  Restrict `addEditableProp` to first level properties only

### ISSUE THREAD

**Issue by oleh-maikovych** [fieldenms/tg#1556]
### Description

Currently Entity Master and EGI-master don't allow one to edit sub-properties of properties of the master entity type. This restriction should be taken into account by EGI-master API when adding the editable property to EGI by `addEditableProp` method. This method should throw meaningful exception that two or more level sub-properties can not be edited by EGI -master. 

### Expected outcome

`addEditableProp` should not allow one to add two or more level sub-properties to EGI-master. And inform about that during entity centre generation.

**Comment by 01es** [comment]
This issue also includes an improvement of key board bindings for autocompeters when editing properties in EGI.
