### ISSUE TITLE
Sanitizing of String parameters in all jasper reports

### ISSUE THREAD

**Issue by julia-fms** [fieldenms/tg#1585]
### Description
It was reported that Jasper reports are producing sub-optimal output due to the presence of tabs in some of the `String` values.

"Helper" class `EntityAggregatesReportSource` is used as an intermediate data container for Jasper reports.
By "sanitizing" `String` values that go through this class, it would be possible to improve the output of a large proportion of Jasper reports - i.e. those that that use `EntityAggregatesReportSource`.

Such sanitizing should:

- [x] 1. Replace tabs and various non-breaking spaces with regular spaces.
- [x] 2. Trim any non-printable characters: spaces (including those that appeared after replacing in step 1), line breaks and carriage returns, from both ends of `String` values.

### Expected outcome
Reduced effect of non-printable characters on the output of printable reports.

**Comment by elvin-fms** [comment]
As discussed and agreed with @01es, processing of `String` values passed to JasperReports will be performed on application level.
