### ISSUE TITLE
JasperReports support library

### ISSUE THREAD

**Issue by elvin-fms** [fieldenms/tg#1587]
### Description
Existing classes and utilities related to JasperReports need to be extracted into a separate TG library.
Actual work is to be performed as part of issue https://github.com/fieldenms/tg-libs/issues/15

### Expected outcome
A separate TG library of classes and utilities to better support integration between TG and JasperReports.

**Comment by 01es** [comment]
This issue should be treated together with issue https://github.com/fieldenms/tg/issues/658.
