### ISSUE TITLE
Tree table component based on iron-list

### ISSUE THREAD

**Issue by oleh-maikovych** [fieldenms/tg#1631]
### Description

Need to implement tree table component based on `iron-list` in order to be able to display and scroll through large amounts of data.

### Expected outcome
Ability to handle large amounts of data, having a hierarchical nature.

**Comment by 01es** [comment]
The core functionality has been implemented and included as part of milestone v1.4.5M11. It is used as the basis for Domain Explorer (#1550). However, this issue remains open awaiting completion of changes that are required to improve Security Matrix.
