### ISSUE TITLE
Web API: misc improvements

### ISSUE THREAD

**Issue by jhou-pro** [fieldenms/tg#1655]
### Description

- [x] Use standard `EntityUtils.isIntrospectionAllowed` method for type filtering
- [x] Remove `*GroupingProperty` special handling as they become synthetic and conform to `EntityUtils.isIntrospectionAllowed`
- [x] Adjust utilities for `Can Read [Model]` tokens generation to conform to `EntityUtils.isIntrospectionAllowed`
- [x] Relax EQL checks to support querying of `id` and `version` for synthetic entities such as  `*GroupingProperty`.
- [x] GraphiQL editor: adjust validation indicators to be compatible with CORS policies (i.e. no `data:image/png;base64`).
- [x] Add support for automated unit testing of default centre configurations creation; this is to catch violations of rules for property inclusion instigated by `@DenyIntrospection` / `@Ignore` annotations.

### Expected outcome
Miscellaneous improvements to the Web API capabilities.

**Comment by 01es** [comment]
Relaxing of EQL checks to support querying of `id` and `version` for synthetic entities has a positive side-effect of allowing to yield and fetch `id` without the need to resort to an approach with `computedId`.
