### ISSUE TITLE
Property Editor: validation warning and error messages to have HTML markup removed

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#1717]
### Description

Validation errors and warnings may contain HTML tags for better representation of those messages when viewed in a separate dialog. However, displaying such messages as part of property editors as a single line does not render HTML and makes HTML tags visible.

Displaying error and warning messages inline with property editors should remove HTML markdown. This will improve how the messages appears to users and would support more text to be visible in the same space.

#### Implementation remarks

The actual validation messages, associated with a validated entity, should remain unchanged. Only the message value that it bound to the editor to be displayed as an error or warning is to have HTML tags stripped. As per comment below, tooltips should retain HTML formatting.

Possible implementation for removing HTML tags could use the capability of a web browser, which works very reliably and correctly handles not only tags, but also special codes such as `&nbsp;`.
```JavaScript
function removeHtmlTags(html) {
   const tmp = document.createElement("DIV");
   tmp.innerHTML = html;
   return tmp.textContent || tmp.innerText || "";
}
```
Alternatively, regex could be used. For example, the following regex removes tags, but not special codes.
```JavaScript
text.replace(/<\/?[^>]+(>|$)/g, "")
```

There could be situation where removing HTML tags could lead to "glueing" for the words separated by tags. For example,
```JavaScript
"<b>title</b><br>some other text<p>yet another text";
```
becomes
```JavaScript
"titlesome other textyet another text"
```
Ideally such situations should be prevented.

### Expected outcome
Ability to see validation errors and warnings without extraneous HTML tags.

**Comment by elvin-fms** [comment]
HTML tags should also remain when the validation message appears as a tooltip:
![image](https://user-images.githubusercontent.com/5975638/209231796-3cd1617d-cff1-4a5c-9d93-5894927d9af8.png)

**Comment by 01es** [comment]
This issue may potentially become redundant if issue #1916 is implemented first.

**Comment by 01es** [comment]
Issue https://github.com/fieldenms/tg/issues/1916 has been implemented and proved to be working well, removing the need in this issue.
