### ISSUE TITLE
EGI: `false` Boolean properties with action should be represented as empty square 

### ISSUE THREAD

**Issue by oleh-maikovych** [fieldenms/tg#1778]
### Description

Yet boolean properties on EGI are represented with `check` icon if it is `true` or empty cell otherwise. Sometimes boolean properties on EGI have action, which changes their state. In that case it would be better to represent `false` boolean properties with empty square and leave `true` values the same. This approach may help user to recognise boolean properties on EGI when all their values are `false`

### Expected outcome

More appropriate visual representation of boolean properties.

**Comment by 01es** [comment]
It was demonstrated that equivalent functionality can be achieved at the application level by using rendering customisers for EGI. Therefore, there is no real need to introduce any special support at the platform level.
