### ISSUE TITLE
Domain Explorer: add missing desc for properties

### ISSUE THREAD

**Issue by nazchk** [fieldenms/tg#1804]
### Description
It turned out that `Desc` value for `property` rows has not been provided as part of the `Domain Explorer` [original implementation](https://github.com/fieldenms/tg/issues/1550).

The following steps should be taken to correct this:

- [x] enhance the `DomainProperty` entity with `desc` property
- [x] ensure that `desc` property values from `DomainProperty` entities are correctly populated during the `Domain Explorer` data population procedure
- [x] ensure that `desc` property values from `DomainProperty` entities are correctly displayed in the `DomainExplorer` tree UI.

### Expected outcome
`Desc` value for `property` rows is provided and displayed in the `DomainExplorer` tree UI.

**Comment by jhou-pro** [comment]
Web test in `tg-reflector.html` needs to be adjusted accordingly to the changes of this issue.
