### ISSUE TITLE
Verifying definitions of Union Entities

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#1915]
### Description

Union entities are entities (i.e., `AbstractUnionEntity` extend `AbstractEntity`) and all verification rules in #1913 and #1914 are applicable. However, it has additional constraints that should be verified:

- [x] 1. There should be 1 or more entity-typed properties.
- [x] 2. Only entity-typed properties are permitted. However, those should not be union entities themselves (i.e., nesting of union entities is not supported).
- [x] 3. There should be at most one property of a particular entity type (i.e., multiple properties of the same entity type are disallowed).

### Expected outcome
Compile time support for verification of definitions for union entities, improving productivity of application developers.

**Comment by homedirectory** [comment]
@01es Do we allow hierarchies of union entity types? If yes, then it affects constraint number 1, should we consider only declared properties or also take inherited ones into account?

**Comment by 01es** [comment]
> @01es Do we allow hierarchies of union entity types? If yes, then it affects constraint number 1, should we consider only declared properties or also take inherited ones into account?

@homedirectory , good question – we do not, and hopefully there will be no need for that.
