### ISSUE TITLE
String key integrity constraints: leading and trailing whitespaces, non-printable characters, commas

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#1931]
### Description

Similar to how all entity-typed properties attract `EntityExistsValidator` by default, it is necessary to introduce a default constraint for `String`-typed keys and key members.

The default constraint should not permit:

- [x] 1. Non-printable characters.
- [x] 2. Leading whitespaces.
- [x] 3. Trailing whitespaces.
- [x] 4. Consecutive whitespace.
- [x] 5. Commas, as commas are used to for separating search strings in selection criteria.

Individual validators are preferred for:
- item 1: `RestrictNonPrintableCharactersValidator`
- items 2-4: `RestrictExtraWhitespaceValidator`
- item 5: `RestrictCommasValidator`

Naturally, these validators should be applicable to properties of type `String`, and can be used when specifying `@BeforeChange`. However, for keys or key-members that are of type `String`, these validators must be present by default (see implementation details below).

In the future, we may need to consider introducing annotation for "relaxing" these validators (i.e., similarly to `SkipEntityExistsValidation`). However, at this stage it is not necessary.

#### Post-implementation details
There was a need to support skipping the default validation for String-typed keys. Annotation`SkipDefaultStringKeyMemberValidation` has been developed for that, which supports full skipping (default) or skipping of only the specified validators. Here is an example how it can be used to skip 2 out of 3 default validators.
```Java
    @IsProperty
    @CompositeKeyMember(1)
    @SkipDefaultStringKeyMemberValidation({RestrictExtraWhitespaceValidator.class, RestrictCommasValidator.class})
    private String title;
```

#### Implementation details

Enum `ValidationAnnotation` would need to be enhanced with 3 new values to represent these validators. This needs to be verified, but potentially there is no need to create the corresponding annotations as there would no practical use for them. It should be possible to pass `null` to the `ValidationAnnotations` constructor for the 3 new enum values.

Then method `AbstractMetaPropertyFactory.create` needs to be enhanced to support instantiation of these 3 validators. However, because they need to be enabled by default, the invocation of `AbstractMetaPropertyFactory.create` would need to be done in `AbstractEntity.collectValidators` with a check, similar to how this is done for `EntityExistsValidator`. Consult line `824` where instantiation of `EntityExistsValidator` gets considered. More specifically:
```Java
if (!validators.containsKey(ValidationAnnotation.ENTITY_EXISTS) && (isEntityExistsValidationApplicable(getType(), field))) { ...
```

----
The logic for these validators can be implemented using regex. Below is an experimental code for matching non-printable chars, leading whitespaces, trailing whitespaces, and consecutive whitespaces. The regex for `patternConsecutiveWhitespaces` matches consecutive whitespaces anywhere, including leading and trailing whitespaces. But if checked last, it will do the trick. In the final code, instances of `Pattern` should be final static members of validators.

```Java
        final Pattern patternNonPrintable = Pattern.compile(".*[^\\p{Print}].*");
        final Pattern patternLeadingWhitespaces = Pattern.compile("\\s+.*");
        final Pattern patternTrailingWhitespaces = Pattern.compile(".*\\s+");
        final Pattern patternConsecutiveWhitespace = Pattern.compile(".*\\s{2,}.*");
        
        final String str = " Word1" + (char) 129 + "  Word2 ";
        
        if (patternNonPrintable.matcher(str).matches()) {
            System.out.println("Contains non-printable chars.");
        }
        if (patternLeadingWhitespaces.matcher(str).matches()) {
            System.out.println("Contains leading spaces.");
        }
        if (patternTrailingWhitespaces.matcher(str).matches()) {
            System.out.println("Contains trailing spaces.");
        }
        if (patternConsecutiveWhitespace.matcher(str).matches()) {
            System.out.println("Contains consecutive spaces (anywhere).");
        }
```

#### Additional considerations
A discussed, it is worth adding validated, but invalid value to an error message with non-printable characters replaced with `{?}`. However, if the length of the value is `>= 64` then the value should not be included into the error message.

Similar could be useful for whitespace, especially the consecutive whitespace.

Also, as a note, consider the fact that characters `\r` and `\n` are considered non-printable. This makes `RestrictNonPrintableCharactersValidator` not applicable to long text properties, such as `desc`.

### Expected outcome
Avoidance of accidental mistakes by user when typing key values.

**Comment by homedirectory** [comment]
@01es 
> Enum ValidationAnnotation would need to be enhanced with 3 new values to represent these validators. This needs to be verified, but potentially there is no need to create the corresponding annotations as there would no practical use for them

I have concluded that there is, in fact, a need to create the corresponding annotations (or a single common one).
`MetaPropertyFull.validate(T, Set<Annotation>, boolean)` accepts a set of *applicable validation annotations*. However, our 3 validators have no annotations associated with them (they have `null` instead), which will lead to them being skipped.
Therefore, we do need to associate some annotation(s) with them despite the lack of practical use.

Another approach would be to leave `ValidationAnnotation` enum untouched. Instead, in `AbstractMetaPropertyFactory.create()` we could add our 3 validators as part of the `@BeforeChange` annotation. If a key-member property already declares `@BeforeChange`, then we could just merge its handlers with our 3 validators, otherwise we simply add `@BeforeChange` implicitly.

**Comment by homedirectory** [comment]
Some examples of validation in property editors:

![image](https://user-images.githubusercontent.com/47361170/221841513-598d280f-86a5-48b7-95c6-a7c69d169896.png)
![image](https://user-images.githubusercontent.com/47361170/221841632-b2df06d6-3bd6-4382-a8a5-694164b5de3e.png)
![image](https://user-images.githubusercontent.com/47361170/221841696-842c326f-79d8-4aa2-a489-727ad900ffb9.png)
![image](https://user-images.githubusercontent.com/47361170/221841763-40a85bc7-675c-466e-894d-af18b59496b2.png)
