### ISSUE TITLE
Web API: concurrent queries lead to field authorisation errors

### ISSUE THREAD

**Issue by jhou-pro** [fieldenms/tg#1937]
### Description

Recently it was reported that concurrent Web API queries (e.g. see below) led to the following error `java.lang.IllegalStateException: org.hibernate.HibernateException: Calling method 'createNativeQuery' is not valid without an active transaction (Current status: NOT_ACTIVE)` and then other errors followed after that (e.g. `org.postgresql.util.PSQLException: This statement has been closed`).

```
2023-Feb-23 13:40:22     INFO GraphQLResource GraphQLResource:85  "Processing POST request..."
2023-Feb-23 13:40:22     INFO GraphQLResource GraphQLResource:85  "Processing POST request..."
2023-Feb-23 13:40:22     INFO GraphQLResource GraphQLResource:85  "Processing POST request..."
2023-Feb-23 13:40:22     INFO GraphQLResource GraphQLResource:85  "Processing POST request..."
2023-Feb-23 13:40:22     INFO GraphQLResource GraphQLResource:85  "Processing POST request..."
2023-Feb-23 13:40:22     INFO GraphQLResource GraphQLResource:85  "Processing POST request..."
2023-Feb-23 13:40:22     INFO GraphQLResource GraphQLResource:85  "Processing POST request..."
```

4 of these requests have failed and 3 completed successfully. Even though it is intermittent and single request always passes successfully, it would be best to avoid these errors.

The query may look as simple as the following:
```
{
  rotable {
    serialNo
  }
}
```

#### Implementation details

It has been determined that single instance of `IAuthorisationModel` is used in all Web API and there is single instance of `SecurityRoleAssociationDao` inside. Current thread sets `Session` of that companion and this `Session` may be overridden by already closed instance with inactive transaction from other thread.

Better to always use new `IAuthorisationModel` instance with separate `SecurityRoleAssociationDao` companion.

### Expected outcome
More reliable running of concurrent Web API queries.

**Comment by 01es** [comment]
@jhou-pro please review my changes. Here is a diagram that should explain their intent.

![image](https://user-images.githubusercontent.com/5511940/222115967-ed9f9360-563a-455d-8639-b9ab887f4819.png)
