### ISSUE TITLE
Synthetic Entities: improved inference for the kind of JOINS

### ISSUE THREAD

**Issue by nazchk** [fieldenms/tg#1976]
### Description

EQL3 uses property requiredness information to decide whether OUTER or INNER joins should be used when generating SQL queries. Currently EQL3 infers the requiredness information from property declarations. This works well for Persistent Entities (PEs), but for Synthetic Entities (SEs) it would be more reliable to infer such information from the underlying SE query model(s). The main reason for this lies in the fact that a lot less care is taken when defining properties in SEs.

### Additional tasks that have been implemented as part of the issue:

- ordering of Synthetic Entities of the Domain according to their inter-dependency (first go those SEs that don't have other SEs in their query model);

- taking into account yields from all models (not only the first one) of query source based on queries to determine its nonnullability and java type;

- refactored the logic of Query Souce Infos caching to be more transparent (by introduction isComprehensive marker)

- implemented more sophisticated inferring of yields nonnullability for nullable properties by analysing `where` statement for explicit `notNull` conditions for given nullable props.

### Expected outcome
Correct joins at the SQL level in cases where property definitions do not reflect the actual data requiredness based on SE query model(s).

**Comment by 01es** [comment]
As discussed with @nazchk and @elvin-fms, 3-4 week for completion is needed for this issue.
