### ISSUE TITLE
Composite key members: a warning upon change

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#2058]
### Description

In general data belongs to 2 main categories -- reference data (aka master data) and transactional data. Examples of reference data include `Workshop`, `Station`, `Service`, `Equipment`, `Task` – data that does not reference many other data and instead is mainly referenced from the transaction data. Examples of transactional data include `WorkOrder`, `PurchaseOrder`, `Issue`, `Receipt`, `Timesheet`, `WorkOrderTask` – data that references a lot of reference data, but is not referenced by by too much other data. Of course, this is a spectrum and some transactional data such as `WorkOrder` can also be considered as reference data as it is referenced by `Timesheet`, `WorkOrderTask`, `Issue`, etc. But at the same time `WorkOrder` is "short lived" – it gets created, progressed and finished. While other data, closer to the reference data end of spectrum, such as `Workshop` not changed much if at all after its initial creation, but remains relevant as long as the physical workshop it represents remains in business.

In TG-based applications the Web UI is structured in such a way that makes it very convenient to open the reference data in the corresponding Entity Masters. And so users with the "Can Save" privilege can easily change that data without realising that what they changed affects all the data referencing that specific value.

In order to make sure that users know what they are doing, it is proposed to introduce a default "soft" integrity constraint for key-member properties as the very last constraint, to be executed after all domain integrity constraints succeeded, that returns a `Warning` advising users that they have changed a key value, which will be reflected in all the data referencing this entity. Such constraint should only be relevant for persisted entities (i.e., persistent and saved) to warn only in case of changes rather than upon its original creation.

- ~[ ] 1.~ The constraint itself could simply always return `Warning` with message: "Saving this change will be reflected in all the data referencing this [entity title].". For example, changing the name of a `Workshop` record would say "Saving this change will be reflected in all the data referencing this [Workshop]."

- [x] 2. (optional, but preferred) We could be a bit smarter and return `Warning` only if there are actual references and we could even enumerate the references by entity type. Entity `ReferenceHierarchy` can be used to obtain the relevant information. The message should contain a header and body separately, where the body would be a html table similar to the one used for reporting an error when de-activation is not possible due to active references. Refer `ActivePropertyValidator` for inspiration.

    <img width="2628" alt="image" src="https://github.com/fieldenms/tg/assets/5511940/9e4ce3af-06d3-4457-8376-62317a13cce1">

- [ ] 3. Add support for type-level annotation `@SkipKeyChangeValidation`.

### Expected outcome
A sensible warning to users upon their attempt to change key values.

**Comment by homedirectory** [comment]
Changing a Rotable's serial number:

![image](https://github.com/fieldenms/tg/assets/47361170/f2b1b326-4203-4c9c-b891-28a85f57e5f1)

**Comment by 01es** [comment]
@homedirectory, we're dealing with changes to the reference values (aka master records) and I think it is worth reporting existing references even if those references represent inactive instances. We could report active and inactive references separately, just to make that fact obvious. However, there is no immediate need for that and once such need arises, it would be best addressed as a separate issue.
