### ISSUE TITLE
Multiline text editor has extra 2 pixel padding

### ISSUE THREAD

**Issue by oleh-maikovych** [fieldenms/tg#2257]
### Description

Recently it was reported that text inside multiline text editor has extra identation from the left side of editor which is inconsistent with other editors. That was caused by extra 2px padding that was addded to standard styles of `textarea`. Please adjust styles of `tg-multiline-text-editor` component to make it consistent with other editors.

### Expected outcome

`tg-multiline-text-editor` shouldn't have any extra identation and should be consistent with other `tg-editor`s

### Actual outcome 

Text inside `tg-multiline-text-editor` has extra identation from left side.

**Comment by 01es** [comment]
Or core issue requirements have been implemented.
