### ISSUE TITLE
Entity Centre: mnemonics API for @CritOnly properties

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#337]
Synthesised entities are used to implement complex on-line reports that require joining of multiple domain entities, often with sophisticated aggregations. As a rule such synthesised entities have so-called `@CritOnly` properties that are used to provide selection criteria with cross-cutting concerns (i.e. the same criteria need to be used when selecting and aggregating several domain entities).

The current functionality for `@CritOnly` does not support the use of selection criteria mnemonics when designing an EQL model behind a synthesised entity. However, having such support would bring `@CritOnly` properties to the same level of rich functionality as ordinary persistent properties. 

This issues covers the development of selection criteria mnemonics API that could be used in application to `@CritOnly` properties when creating an EQL model for synthesised entities.

**Comment by nazchk** [comment]
Issue #947 is the solution to the problem described in this issue.

**Comment by 01es** [comment]
Implemented as #947.
