### ISSUE TITLE
EQL source yield: should allow direct yield of NULL values with JDBC type determination

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#622]
### Description

There are cases where polymorphic entities need to be queried or represented as a single entity with united properties. This can be achieved by devising a synthesised entity selecting the union of properties from a number of EQL models, each pertaining to a specific entity subtype.

Each of such submodel needs to `yield` all of the united properties whereas non-existing for a specific subtype properties should be yielded as `null` or as a specific primitive value -- `.yield().val(null).as("missingProperty")` or `.yield().val(true).as("missingBooleanProperty")`. 

Unfortunately, the resultant SQL does not get properly executed for all currently supported RDBMS due to the inability by the JDBC driver to automatically determine the expected data type for such values. Hence, it is required to overcome this limitation by yielding an explicit `caseWhen` with `endAsXXX` (where `XXX` is a type).

This issue should cover the development of a more comprehensive `yield` implementation (hopefully with no API changes) that would automatically determine the required type from the context.
### Expected outcome

More intuitive EQL API for constructing synthesised entities.
### Actual outcome

Needs the use of workarounds such as:

``` Java
yield().beginExpr().caseWhen().val(null).isNull().then().val(false).endAsBool().endExpr().as("certified")
```
### Steps to reproduce

Create a synthetic entity with `.yield().val(null).as("property")`. Executing such query under H2 results in "could not determine type for ?" error.

**Comment by nazchk** [comment]
Issue #1210 is the solution to the problem described in this issue.

**Comment by nazchk** [comment]
Covered by #1210.
