### ISSUE TITLE
Enhance existing database schema generation to also generate unique indexes for key properties

### ISSUE THREAD

**Issue by elvin-fms** [fieldenms/tg#670]
### Description

While #313 is still in progress, we are coping using the existing database schema generation. However, one place where it is noticeably lacking is unique indexes for key properties.
It would be nice to implement this as a "stop-gap" measure while waiting for #313.

### Expected outcome

Generation of unique indexes like the ones below:

``` SQL
CREATE UNIQUE INDEX KUI_WATYPE_ ON WATYPE_(KEY_);
CREATE UNIQUE INDEX KUI_LOCATIONSUBSYSTEM_ ON LOCATIONSUBSYSTEM_(LOCATION_, SUBSYSTEM_);
```

**Comment by 01es** [comment]
The required functionality has been implemented as part of #313, which is already merged into `develop`.
