### ISSUE TITLE
Activatable Entity: support deletion

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#678]
### Description

There are cases where activatable entities need to be deleted while still being active. Such deletion needs to be semantically equivalent to making an entity instance inactive in order to decrement reference counts for other activatable entity instances that are referenced by this instance. An activatable entity could only be deleted after decrementing the relevant reference counts.

The actual use case for this requirements comes from TTGAMS were it should be possible to delete timesheet instances that are active (entered status). Such timesheet instances hold references to personnel entity instances, which are also activatable and thus have their `refCount` increased by active timesheet entries.
### Expected outcome

The ability to correctly delete activatable entities, which ensures correct handling of the dependent activatable entities.

**Comment by elvin-fms** [comment]
@01es A question in relation to this issue: in TTGAMS, activatable entity `Rotable` has two properties of type `Supplier`, which is also activatable entity.
When an instance of `Rotable` refers to the same `Supplier` via both properties - does this count as one or two `refcount`?
For now I will assume that one, please advise if this is not true.

**Comment by 01es** [comment]
@elvin-fms Please refer commit 7325517c5 in response to your question.
