### ISSUE TITLE
Criteria Generator: incorrect handling of @EntityExists annotation

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#706]
### Description
Annotation `@EntityExists` was used in the past to annotate setters for validating an existence of the values being assigned to entity-typed properties. The presence of this annotation was also used by the `CriteriaGenerator` to generate criteria that correspond to properties `@CritOnly(Type.SINGLE)` so that the same validation would also be applied to the associated selection criteria.

Method `CriteriaGenerator.generateSingleCriteriaProperty` needs to be modified to be base on annotation `@SkipEntityExistsValidation`, which has an opposite to `@EntityExists` meaning.

### Expected outcome
Correct implementation of the selection criteria generation logic.

**Comment by jhou-pro** [comment]
This issue is superceded by #990 and its parent #979. All requirements are now satisfied.
