### ISSUE TITLE
Enhance Deletion and Deactivation with Dependency Analysis

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#74]
Need to provide a way for obtaining a list of dependencies for an entity that:

- [x] 1. Is attempted to be deleted, but cannot be deleted due to existing dependencies. 
- [x] 2. Is attempted to be made inactive, but cannot be made inactive due to existing active dependencies. 

Such feature would provide users with convenient information and a way to make the right decision upon trying to delete an entity.

A convenient UI integration for such feature should be provisioned, but covered by a separate issue that would specify how exactly such integration should work.

This issue should cover both non-activatable and activatable entities.

**Comment by nazchk** [comment]
Support for displaying a detailed deletion error message that would include the relevant dependencies should be covered by a separate issue.
