### ISSUE TITLE
Enhance Compound master API to capture master entity into the context

### ISSUE THREAD

**Issue by elvin-fms** [fieldenms/tg#797]
### Description
`Compound.openNew()` was originally implemented to capture selection criteria into the context. There are, however, situations that require a master entity to be present in the context. For example, cases where a new entity with a compound master needs to be created from an embedded centre of some other compound master.

### Expected outcome
The ability to use the master entity for initialisation of the child entity where the child entity is represented by a compound master.

**Comment by elvin-fms** [comment]
Requires client-side handling.

**Comment by 01es** [comment]
After discussing the required functionality, it has become apparent that it is only required to provide new factory `Compound.openNewWithMasterEntity()`. The previous changes should be reverted.
