### ISSUE TITLE
Warnings Acknowledgement: required errors to be checked before warnings acknowledgement

### ISSUE THREAD

**Issue by jhou-pro** [fieldenms/tg#820]
### Description
Warning acknowledgement dialog should be displayed only if the entity being saved has no erroneous properties due to their requiredness. 

At the moment the decision to display this dialog happens before entity validation and is based solely on the presence of past validation errors and current warnings. However, errors should always take precedence over warnings.

### Expected outcome
Requiredness related errors should always manifest before any warning acknowledgement.

**Comment by jhou-pro** [comment]
Simplistic functional entities (that trigger detail centres for example) becomes invalid after moving full-validation at early stage of saving.

**Comment by 01es** [comment]
As discussed, branch `Issue-#820-take-2` should be deleted -- a single commit there is not needed.
