### ISSUE TITLE
EGI: visual cues for sorting, action and editing

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#835]
### Description

Currently, data ordering (aka sorting) configuration can only be seen if the "sorting" action dialog. Similarly, properties in EGI can have actions that get performed when tapping corresponding cells. But there is no visual cue that would indicate if property has an action unless tapped or a tool tip displayed, which requires a mouse pointer to hover over the cell. Also with introduction of in-place editing in EGI, there is no visual cue to indicate what properties are editable.

This issue enable indications for three situations:

- [x] Sorting order indicator (both desc/asc and ordering position).

- [x] Presence of an action, indicated as the "finger" mouse pointer icon.

- [x] Editability, indicated with the "pencil" icon.

Columns with indicators should get shorter than the space required to fully display indicators present. Their position should be on the righthand side for both left and right justified header titles.

### Expected outcome
Visual cues to improve EGI UX.

**Comment by mouatt** [comment]
I noticed that these visuals are part of milestone 20191213 in our Test environment. The visual for sorting makes sense as this is just an indicator but is the "finger" icon meant to do something because it doesn't seem to work?

The other thing I've noticed is that with the introduction of these icons a lot of column headings that were previously fully visible are now obscured (in some cases the heading label is completely obscured) which requires the user to increase the size of the column width so they can see the column heading fully.
This will have a negative impact on users and will need to be addressed before deploying into our production environment.

**Comment by 01es** [comment]
@mouatt 
> The visual for sorting makes sense as this is just an indicator but is the "finger" icon meant to do something because it doesn't seem to work?

As per issue description, these are just visual cues. The "finger" icon indicates presence of a tap action for column values. Clicking/tapping values in columns with the "finger" icon in their header opens a corresponding Entity Master and details dialog.




> The other thing I've noticed is that with the introduction of these icons a lot of column headings that were previously fully visible are now obscured (in some cases the heading label is completely obscured) which requires the user to increase the size of the column width so they can see the column heading fully.
> This will have a negative impact on users and will need to be addressed before deploying into our production environment.

Thank you for this early feedback. It looks like the majority of cases with the negative impact is in relation to columns that have both the "finger" and "sort" icons present at the same time (it is very unlikely for the "sort" icon to be displayed in conjunction with the "pencil" icon). 

The following two options together should address the problem outlined:

1. If the "finger" icon does not seem to be too valuable then it can be removed completely. This would effectively leave only the "sort" icon.

2. Currently if users add/remove sorting for a property, the width of the corresponding column is not affected. Hence the overlap of the "sort" icon with the column title. This can be changed by dynamically increasing the width of columns to fit the "sort" icon when it needs to be displayed, and decreasing when it is no longer displayed (i.e. sorting was removed).

Please let us know if you agree with the proposed approach.

**Comment by mouatt** [comment]
Sorry I thought the heading icons may have been functionality similar to Excel where you could click on a column heading and change the sorting etc.
I think the two steps above will fix the issues with column headings.

**Comment by 01es** [comment]
> Sorry I thought the heading icons may have been functionality similar to Excel where you could click on a column heading and change the sorting etc.

As it often happens in enterprise applications, sorting is applied to large datasets and on multiple properties for complex data queries. This is why specifying data ordering is done using the column customiser dialog where multiple properties can be added to the sorting "spec" including sorting directions (asc/desc) and the actual effect takes place after applying all changes.

> I think the two steps above will fix the issues with column headings.

Thank you. Issue #1474 has been created to capture these changes. Please review the "Remarks" section in this issue. Dynamic width adjustment for columns may introduce some different UX impediments.
