### ISSUE TITLE
EGI needs to support efficient data model updates

### ISSUE THREAD

**Issue by 01es** [fieldenms/tg#884]
### Description
EGI already supports a programatic way to update its data model, which is used for interactive UX where, for example, changing a chart leads to changes in an EGI instance that represents the same or derived information. However, the current implementation is inefficient and relies on updating of the whole data model. This result in poor performance that is not adequate for real-time interaction.

The EGI API (JS) needs to be developed that would enable efficient updates to the underlying data model by means of notifying what specific entities and properties have been updated and need to be refreshed/redrawn in EGI.

### Expected outcome
Efficient updates to the underlying data model of EGI that enables building real-time interactive functionality.

**Comment by 01es** [comment]
EGI can be communicated efficiently about the underlying data changes by firing event "tg-entity-changed" with a JSON load that contains changed entities and an array of modified properties in those entities that need to be re-drawn.

```JavaScript
this.fire("tg-entity-changed", {entities: entities, properties: ["scheduledStart", "scheduledFinish"]});
```
*TODO:* The above even firing snippet need to be explained in greater detail.

**Comment by oleh-maikovych** [comment]
The code snippet below

```JavaScript
this.fire("tg-entity-changed", {entities: entities, properties: ["scheduledStart", "scheduledFinish"]});
```
fires `tg-entity-chnaged` event with `event.detail` equal to object that should have entities changed and what properties in those entities were changed (`{entities: entities, properties: ["scheduledStart", "scheduledFinish"]}`). The event gets propagated up to entity centre and is handled in `tg-entity-centre-behavior`

```JavaScript
self.addEventListener("tg-entity-changed", function(e) {
     e.detail.entities.forEach(entity => {
           e.detail.properties.forEach(prop => this.$.egi.updateEntity(entity, prop));
     });
}.bind(self));
```

The entity centre calls `updateEntity` on EGI.
