### ISSUE TITLE
Bind selection criteria entity to  insertion point

### ISSUE THREAD

**Issue by oleh-maikovych** [fieldenms/tg#897]
### Description

- [x] 1. Need to provide binding for the selection criteria binding entity to entity centre's insertion point in the same way as `retrievedEntities` were bound to the insertion point. This will enable access to selection criteria values from insertion points.

- [x] 2. Also need to introduce some for the case when new `retrievedEntities` were retrieved via entity centre run, refresh or page navigation.

**Comment by 01es** [comment]
@oleh-maikovych could you please clarify the second item -- "need to introduce some <?> for the case...". Some what?
