### ISSUE TITLE
Enhance EGI - insertion point selection API for multi selection support.

### ISSUE THREAD

**Issue by oleh-maikovych** [fieldenms/tg#899]
### Description

In order to sync entity selection in EGI and insertion point there was introduced `retrievedEntitySelection` property in entity centre behavior that is monitored by interested insertion points and EGI. This property allows only to set selection for only one entity. It was good enough for GIS component. Not it is required to enhance this behavior so that multiple entities can be selected or deselected using this API property.

**Comment by 01es** [comment]
Commit 19f202075c5b51c621a relates to this issue.
