### ISSUE TITLE
Entity Centre: support for polymorphic masters

### ISSUE THREAD

**Issue by jhou-pro** [fieldenms/tg#967]
### Description

Need to add simple API to support `EGI` entities editing through polymorphic masters including compound ones. Such support partially exists for the case of using simple masters (through generic `EntityEditAction`).

See issue fieldenms/TTGAMS#732.

### Expected outcome

Being able to edit polymorphic entities through different kinds of masters including compound / simple ones.

**Comment by 01es** [comment]
This functionality was implemented in a different way.
