### ISSUE TITLE
EGI shortcuts to be invoked from insertion points

### ISSUE THREAD

**Issue by jhou-pro** [fieldenms/tg#977]
### Description
In case where centre's insertion point has been focused there is no way to invoke parent centre's shortcut. This is very inconvenient for the user especially in cases where insertion point is a) long and scrolled down b) maximised.

### Expected outcome
Being able to invoke parent centre's actions through shortcuts from insertion points.

**Comment by 01es** [comment]
Need to provide a more reliable mechanism of handling shortcuts by means of a callback.
